#!/bin/bash
# Host: generate a script that runs ON the stock Android panel (bash 3.2 + busybox)
# and fetches the card-stage payload over HTTP with no adb: 64 MiB chunk files of the
# raw p2 image -> /dev/block/mmcblk0p2 (dd seek, fsync, sha256 per chunk, 3 tries),
# then the payload files -> DEST, verified against SHA256SUMS (rootfs archive skipped).
# Start it from the UART root shell:  busybox wget -q -O /logs/panel-fetch.sh URL/panel-fetch.sh
#   nohup /system/bin/bash /logs/panel-fetch.sh > /logs/panel-fetch.log 2>&1 &
#   steps/mkpanelfetch.sh IMAGE CHUNKDIR STICKDIR URLBASE_CHUNKS URLBASE_STICK [DEST] > panel-fetch.sh
set -euo pipefail
IMG=${1:?}; CDIR=${2:?}; SDIR=${3:?}; UC=${4:?}; US=${5:?}; DEST=${6:-/logs/tsx-payload}
CONF=$SDIR/tsx-install/tsx-install.conf; P2REL=$(sed -n 's/^ROOTFS_P2=//p' "$CONF")
FULL=$(sha256sum "$IMG" | cut -d' ' -f1); MIB=$(( $(stat -c %s "$IMG") / 1048576 ))
cat <<H
#!/system/bin/bash
# generated by mkpanelfetch.sh $(date '+%F %T'); image $FULL ($MIB MiB)
BB=/system/bin/busybox; DEV=/dev/block/mmcblk0p2; DEST=$DEST
say() { echo "\$(\$BB date '+%T') \$*"; }
fetch_chunk() {  # name off cnt want
	local t=0 got
	while :; do t=\$((t+1))
		\$BB wget -q -O - "$UC/\$1" | \$BB dd of=\$DEV bs=1048576 seek=\$2 conv=notrunc,fsync 2>/dev/null
		got=\$(\$BB dd if=\$DEV bs=1048576 skip=\$2 count=\$3 2>/dev/null | \$BB sha256sum | \$BB cut -d' ' -f1)
		[ "\$got" = "\$4" ] && { say "chunk \$1 ok (MiB \$2..\$((\$2+\$3-1)))"; return 0; }
		say "chunk \$1 MISMATCH \$got (try \$t)"; [ \$t -lt 3 ] || return 1
	done
}
say "== p2 chunks"
H
off=0
for c in $(cd "$CDIR" && /bin/ls | sort); do
	sz=$(stat -c %s "$CDIR/$c"); cnt=$((sz / 1048576)); h=$(sha256sum "$CDIR/$c" | cut -d' ' -f1)
	echo "fetch_chunk $c $off $cnt $h || { say FAILED; exit 1; }"
	off=$((off + cnt))
done
cat <<H
say "== full readback of $MIB MiB"
\$BB sync; echo 3 > /proc/sys/vm/drop_caches
got=\$(\$BB dd if=\$DEV bs=1048576 count=$MIB 2>/dev/null | \$BB sha256sum | \$BB cut -d' ' -f1)
[ "\$got" = "$FULL" ] && say "p2 OK $FULL" || { say "p2 FULL MISMATCH \$got"; exit 1; }
say "== payload files -> \$DEST"
\$BB mkdir -p "\$DEST"
H
(cd "$SDIR" && find . -type f ! -path "./$P2REL" ! -path './tsx-install/backup/*' ! -path './tsx-install/log/*' | sed 's#^\./##' | sort) | while IFS= read -r f; do
	echo "\$BB mkdir -p \"\$DEST/$(dirname "$f")\"; \$BB wget -q -O \"\$DEST/$f\" \"$US/$f\" || { say \"wget $f FAILED\"; exit 1; }"
done
cat <<H
cd "\$DEST" && \$BB grep -v "  $P2REL\$" tsx-install/SHA256SUMS > /logs/sums.in && \$BB sha256sum -c /logs/sums.in > /logs/sums.out 2>&1 \\
	&& say "files OK (\$(\$BB grep -c ': OK' /logs/sums.out) verified)" || { say "files MISMATCH: \$(\$BB grep -v ': OK' /logs/sums.out | \$BB head -n 3)"; exit 1; }
say "ALL DONE"
H
